workflows:
  ios-voice-avatar:
    name: Voice Avatar iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "VoiceAvatarApp.xcodeproj"
        XCODE_SCHEME: "VoiceAvatarApp"
        BUNDLE_ID: "com.voiceavatar.app"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build for simulator
        script: |
          xcodebuild build -project "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -destination "generic/platform=iOS Simulator" CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
